### ISSUE TITLE
snaps to wrong place

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/spring-input#1]
to reproduce:
1. place input at 0
2. start dragging from far right of screen toward the left
3. cursor will snap to the right edge

**Comment by Qix-** [comment]
Snapping is weird altogether. Even if I drop it at one direct spot, it still snaps to a random place, as if it forces some sort of residual velocity.

**Comment by mattdesl** [comment]
@Qix- Yeah, I see it. Will look into that too. :smile:

**Comment by mattdesl** [comment]
@Qix- I fixed the velocity a bit. There was a bug where it would always have momentum on release even if you were holding it still. The new version should also has some tighter defaults:
http://mattdesl.github.io/spring-input/

**Comment by Qix-** [comment]
Much much better :+1:
